[2024-12-19 12:10:37,509] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: run_python_script_dag.run_python_script 2024-12-19T12:01:12.203352+00:00 [queued]>
[2024-12-19 12:10:37,527] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: run_python_script_dag.run_python_script 2024-12-19T12:01:12.203352+00:00 [queued]>
[2024-12-19 12:10:37,527] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-19 12:10:37,527] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-19 12:10:37,527] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-19 12:10:37,545] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): run_python_script> on 2024-12-19T12:01:12.203352+00:00
[2024-12-19 12:10:37,549] {standard_task_runner.py:52} INFO - Started process 8925 to run task
[2024-12-19 12:10:37,554] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'run_python_script_dag', 'run_python_script', '2024-12-19T12:01:12.203352+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/creation.py', '--cfg-path', '/tmp/tmpoujl0tz7', '--error-file', '/tmp/tmp5xhrr7ih']
[2024-12-19 12:10:37,555] {standard_task_runner.py:77} INFO - Job 2: Subtask run_python_script
[2024-12-19 12:10:37,629] {logging_mixin.py:104} INFO - Running <TaskInstance: run_python_script_dag.run_python_script 2024-12-19T12:01:12.203352+00:00 [running]> on host 837a3c72cb91
[2024-12-19 12:10:37,730] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=run_python_script_dag
AIRFLOW_CTX_TASK_ID=run_python_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-19T12:01:12.203352+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-19T12:01:12.203352+00:00
[2024-12-19 12:10:37,736] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-19 12:10:37,737] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python tableCreation.py']
[2024-12-19 12:10:37,753] {subprocess.py:75} INFO - Output:
[2024-12-19 12:10:37,882] {subprocess.py:79} INFO - python: can't open file 'tableCreation.py': [Errno 2] No such file or directory
[2024-12-19 12:10:37,884] {subprocess.py:83} INFO - Command exited with return code 2
[2024-12-19 12:10:37,902] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2024-12-19 12:10:37,917] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=run_python_script_dag, task_id=run_python_script, execution_date=20241219T120112, start_date=20241219T121037, end_date=20241219T121037
[2024-12-19 12:10:37,966] {local_task_job.py:151} INFO - Task exited with return code 1
