[2024-12-23 10:30:08,595] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: run_python_script_dag.run_python_script 2024-12-23T10:30:07.335016+00:00 [queued]>
[2024-12-23 10:30:08,631] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: run_python_script_dag.run_python_script 2024-12-23T10:30:07.335016+00:00 [queued]>
[2024-12-23 10:30:08,631] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 10:30:08,631] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-23 10:30:08,631] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 10:30:08,645] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): run_python_script> on 2024-12-23T10:30:07.335016+00:00
[2024-12-23 10:30:08,655] {standard_task_runner.py:52} INFO - Started process 1299 to run task
[2024-12-23 10:30:08,667] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'run_python_script_dag', 'run_python_script', '2024-12-23T10:30:07.335016+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/creation.py', '--cfg-path', '/tmp/tmpiwi6we1x', '--error-file', '/tmp/tmp90ht0hg2']
[2024-12-23 10:30:08,668] {standard_task_runner.py:77} INFO - Job 5: Subtask run_python_script
[2024-12-23 10:30:08,785] {logging_mixin.py:104} INFO - Running <TaskInstance: run_python_script_dag.run_python_script 2024-12-23T10:30:07.335016+00:00 [running]> on host 21ac49de6db4
[2024-12-23 10:30:09,059] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=run_python_script_dag
AIRFLOW_CTX_TASK_ID=run_python_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T10:30:07.335016+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-23T10:30:07.335016+00:00
[2024-12-23 10:30:09,060] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-23 10:30:09,061] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python tableCreation.py']
[2024-12-23 10:30:09,080] {subprocess.py:75} INFO - Output:
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO - Traceback (most recent call last):
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -   File "tableCreation.py", line 29, in <module>
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -     createTable()
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -   File "tableCreation.py", line 23, in createTable
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -     """)
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -   File "/home/***/.local/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 233, in execute
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO -     raise errors.ProgrammingError("Cursor is not connected")
[2024-12-23 10:30:09,722] {subprocess.py:79} INFO - mysql.connector.errors.ProgrammingError: Cursor is not connected
[2024-12-23 10:30:09,746] {subprocess.py:83} INFO - Command exited with return code 1
[2024-12-23 10:30:09,769] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2024-12-23 10:30:09,773] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=run_python_script_dag, task_id=run_python_script, execution_date=20241223T103007, start_date=20241223T103008, end_date=20241223T103009
[2024-12-23 10:30:09,823] {local_task_job.py:151} INFO - Task exited with return code 1
