[2024-12-23 10:50:01,283] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:40:00+00:00 [queued]>
[2024-12-23 10:50:01,312] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:40:00+00:00 [queued]>
[2024-12-23 10:50:01,313] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 10:50:01,313] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-23 10:50:01,313] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-23 10:50:01,339] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): warsaw_data_update_dag_script> on 2024-12-23T10:40:00+00:00
[2024-12-23 10:50:01,349] {standard_task_runner.py:52} INFO - Started process 2303 to run task
[2024-12-23 10:50:01,358] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'warsaw_data_update_dag', 'warsaw_data_update_dag_script', '2024-12-23T10:40:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/warsaw.py', '--cfg-path', '/tmp/tmpv83qus_q', '--error-file', '/tmp/tmp6je87w36']
[2024-12-23 10:50:01,358] {standard_task_runner.py:77} INFO - Job 9: Subtask warsaw_data_update_dag_script
[2024-12-23 10:50:01,559] {logging_mixin.py:104} INFO - Running <TaskInstance: warsaw_data_update_dag.warsaw_data_update_dag_script 2024-12-23T10:40:00+00:00 [running]> on host 21ac49de6db4
[2024-12-23 10:50:01,658] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=warsaw_data_update_dag
AIRFLOW_CTX_TASK_ID=warsaw_data_update_dag_script
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T10:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T10:40:00+00:00
[2024-12-23 10:50:01,659] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-23 10:50:01,660] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts/ && python warsawUpdate.py']
[2024-12-23 10:50:01,672] {subprocess.py:75} INFO - Output:
[2024-12-23 10:50:02,754] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - /home/***/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openweathermap.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO -   InsecureRequestWarning,
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:40:00', 'hour': '10:40:00', 'temperature': 6.81}
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - Error: 1054 (42S22): Unknown column 'time' in 'field list'
[2024-12-23 10:50:02,755] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:42:23', 'hour': '10:42:23', 'temperature': 12.21}
[2024-12-23 10:50:02,756] {subprocess.py:79} INFO - Error: 1054 (42S22): Unknown column 'time' in 'field list'
[2024-12-23 10:50:02,756] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:44:23', 'hour': '10:44:23', 'temperature': 4.15}
[2024-12-23 10:50:02,756] {subprocess.py:79} INFO - Error: 1054 (42S22): Unknown column 'time' in 'field list'
[2024-12-23 10:50:02,756] {subprocess.py:79} INFO - Transformed data: {'date': '2024-12-23 10:41:00', 'hour': '10:41:00', 'temperature': 3.42}
[2024-12-23 10:50:02,756] {subprocess.py:79} INFO - Error: 1054 (42S22): Unknown column 'time' in 'field list'
[2024-12-23 10:50:02,778] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-23 10:50:02,835] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=warsaw_data_update_dag, task_id=warsaw_data_update_dag_script, execution_date=20241223T104000, start_date=20241223T105001, end_date=20241223T105002
[2024-12-23 10:50:02,880] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23 10:50:03,101] {local_task_job.py:151} INFO - Task exited with return code 0
